#! /bin/bash

# colors
bg=#282a36
black=#1e222a
green=#7eca9c
white=#abb2bf
grey=#282c34
blue=#7aa2f7
red=#d47d85
darkblue=#668ee3

interval=0

_wlan() {
    # iw dev wlp3s0 info | grep ssid | awk '{print $2}'
    case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	    up) printf "^c$blue^ ^b$bg^  %s" "Up ^d^" ;;
	    down) printf "^c$blue^ ^b$bg^ ﲁ %s" "Down ^d^" ;;
    esac
}

_batt() {
    get_capacity="$(cat /sys/class/power_supply/BAT0/capacity)"
    printf "^c$green^  $get_capacity%% "
}

_date() {
    printf "^c#ff63dd^^b#282a36^  $(date '+%b %d ^d^^c#d444fc^  %H:%M')%s" " ^d^"
}

_vol() {
    printf "^c#aa00ff^ 墳 $(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')%s" "%^d^"
}

_mem() {
    printf "^c#95ff49^^b#282a36^  $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)%s" " ^d^"
}

_cpu() {
    printf "^c#ff6060^  $(top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\([0-9.]*\)%* id.*/\1/' | awk '{print 100 - $1}')%s" "% ^d^"
}

# _updates() {
#     # updates=$(checkupdates | wc -l)   # arch , needs pacman contrib
#     updates=$(xbps-install -un | wc -l) # void
#     # updates=$(aptitude search '~U' | wc -l)  # apt (ubuntu,debian etc)
#     if [ -z "$updates" ]; then
#         printf "^c#3d6dff^^b#282a36^  0 updates%s" " ^d^"
#     else
#         printf "^c#3d6dff^^b#282a36^  $updates updates%s" " ^d^"
#     fi
# }

_keyboard() {
    layout=$(setxkbmap -query | grep layout | awk '{print $2}')
    printf "^c$darkblue^^b$bg^  $layout%s" " ^d^"
}

while :; do
    [ $interval == 0 ] || [ $(($interval % 3600)) == 0 ] && _updates=$(_updates)
    interval=$((interval + 1))

    sleep 1 && xsetroot -name "$(_keyboard)$(_cpu)$(_mem)$(_vol)$(_wlan)$(_batt)$(_date)"
done
